/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:92c93465-925f-43a6-a20d-65d973d7707a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vuKrXGm7F",
    "aws_user_pools_web_client_id": "2g3qq0jqttd7l9aft3qmm3dua5",
    "oauth": {}
};


export default awsmobile;
